# 科目一多航点列表。
# 第一次测试只保留 1 个航点，距离起点 3~5 m。
# 确认方向、定位、避障正常后，再逐渐增加航点。


subject1_waypoints:
  waypoints:    
    # - name: wp_01
    #   latitude_deg: 38.9866498299
    #   longitude_deg: 117.3427974
    #   altitude_m: 21.741

    - name: wp_02
      latitude_deg: 38.9866743
      longitude_deg: 117.34292644
      altitude_m: 21.741
  
    - name: wp_03
      latitude_deg: 38.98704746
      longitude_deg: 117.34297782
      altitude_m: 21.741
    
    - name: wp_04
      latitude_deg: 38.9866743
      longitude_deg: 117.34292644
      altitude_m: 21.741

    - name: wp_05
      latitude_deg: 38.9866498299
      longitude_deg: 117.3427974
      altitude_m: 21.741