# 科目一多航点列表。
# 第一次测试只保留 1 个航点，距离起点 3~5 m。
# 确认方向、定位、避障正常后，再逐渐增加航点。


subject1_waypoints:
  waypoints:    
    - name: wp_03
      latitude_deg: 38.98670724
      longitude_deg: 117.341834446
      altitude_m: 21.741

    - name: wp_04
      latitude_deg: 38.98665879
      longitude_deg: 117.34196771
      altitude_m: 21.741
  
  
    - name: wp_05
      latitude_deg: 38.98668821
      longitude_deg: 117.3420233745
      altitude_m: 21.741
    
    - name: wp_06
      latitude_deg: 38.98670724
      longitude_deg: 117.341834446
      altitude_m: 21.741