# Settings of the plugins. (The plugins should be stored in script/plugins)

# min_filter fills in minimum value around the invalid cell.
min_filter:
  enable: true                                # weather to load this plugin
  fill_nan: false                             # Fill nans to invalid cells of elevation layer.
  is_height_layer: true                       # If this is a height layer (such as elevation) or not (such as traversability)
  layer_name: "min_filter"                    # The layer name.
  extra_params:                               # This params are passed to the plugin class on initialization.
    dilation_size: 1                         # The patch size to apply
    iteration_n: 30                           # The number of iterations
# Apply smoothing.
smooth_filter:
  enable: true
  fill_nan: false
  is_height_layer: true
  layer_name: "smooth"
  extra_params:
    input_layer_name: "min_filter"
# Apply inpainting using opencv
inpainting:
  enable: true
  fill_nan: false
  is_height_layer: true
  layer_name: "inpaint"
  extra_params:
    method: "telea"                           # telea or ns
# Apply smoothing for inpainted layer
erosion:
  enable: true
  fill_nan: false
  is_height_layer: false
  layer_name: "erosion"
  extra_params:
    input_layer_name: "traversability"
    dilation_size: 3
    iteration_n: 20
    reverse: true
